### ISSUE TITLE
segfault on install/test

### ISSUE THREAD

**Issue by adaptiveoptics** [jonathanstowe/JSON-Name#1]
I've noticed this a couple times now... on my local machine here, and on Travis when an environment's dependencies are being built...

When JSON::Fast is a dependency, and it pulls in JSON::Name , a segfault can happen. The second time I ran it on the machine here, it passed through just fine though, strangely. I'm not sure if Travis will, but I'm going to try it. I doubt it since Travis will be a clean environment each try. The Travis log where it dies is:

$ zef install --/test --depsonly .
===> Searching for missing dependencies: Cookie::Baker, Crust, Digest::SHA, Crust::Middleware::Session, JSON::Fast
===> Updated cpan mirror: https://raw.githubusercontent.com/ugexe/Perl6-ecosystems/master/cpan.json
===> Updated p6c mirror: http://ecosystem-api.p6c.org/projects.json
===> Searching for missing dependencies: URI::Encode, Base64, HTTP::Server::Tiny, File::Temp, HTTP::MultiPartParser, Hash::MultiValue, Getopt::Tiny, HTTP::Easy, URI::Escape, HTTP::UserAgent, Backtrace::AsHTML, Apache::LogFormat
===> Searching for missing dependencies: HTTP::Status, DateTime::Parse, Encode, MIME::Base64, IO::Capture::Simple, Test::Util::ServerPort, PSGI, Test::META, File::Directory::Tree, HTTP::Parser, IO::Blob, HTTP::Tinyish, DateTime::Format
===> Searching for missing dependencies: META6
===> Searching for missing dependencies: JSON::Class
===> Searching for missing dependencies: JSON::Marshal, JSON::Unmarshal
===> Searching for missing dependencies: JSON::Name
/home/travis/.travis/job_stages: line 54:  5355 Segmentation fault      (core dumped) zef install --/test --depsonly .
The command "zef install --/test --depsonly ." failed and exited with 139 during .

I'm blaming JSON::Name because it was the last thing listed. Other than zef. Maybe it's zef? ;)

**Comment by adaptiveoptics** [comment]
Yup - just tried Travis again and it segfaulted again:

===> Searching for missing dependencies: JSON::Name

/home/travis/.travis/job_stages: line 54:  5348 Segmentation fault      (core dumped) zef install --/test --depsonly .

**Comment by jonathanstowe** [comment]
Well, it can't be JSON::Name itself as at that point zef is only searching for the module in the projects.json data (or wherever it gets the module metadata from,)  and the module isn't even downloaded so it's likely that ```zef``` is doing something that is causing Moar to segfault, which is still worrying.  it could just be memory exhaustion or something similar.

In the first instance I woulld suggest running ```zef```  with ```perl6-gdb-m``` (it would probably be worth getting the advice of @ugexe on how best to do this,) to get a backtrace from the segfault and filing a rakudobug about this, as at core this is a problem with moarvm (II am absolutely certain there is no native call involved that could cause this.)

BTW JSON::Name is not a dependency of JSON::Fast, it is a dependency of JSON::Marshal and JSON::Unmarshal which are being brought in the dependency tree of Test::META.

**Comment by adaptiveoptics** [comment]
The strange part is... if you run this on a normal machine and let it die... then run the install again... it works, and doesn't segfault a second time.

But on Travis it's always pristine, so whatever benefit there is to dying is lost. ;)

**Comment by ugexe** [comment]
It's probably an issue related to rakudo 2017.06

You could try:
* using rakudo `2017.05`
* breaking it into smaller parts `zef install HTTP::UserAgent && zef --deps-only install .`

(FWIW I'm able to install the module on the latest rakudo on a linux vm, so its probably specific dependent)

I suspect it ultimately has something to do with the number of processes that have been spawned (and/or the handles associated with them) due to 2017.06 having a bunch of Proc changes. You might experiment and try:
* running the command a second time on travis to see if it works
* `~/zef $ perl6-gdb-m -Ilib bin/zef --deps-only install Crust::Middleware::Session::Store::DBIish`

**Comment by adaptiveoptics** [comment]
OK. Using the 2017.06 - pristine build of it on a pristine Debian 9 VM...

zef install Crust::Middleware::Session::Store::DBIish

It got past the place where it segfaults then died a normal death on HTTP::Server::Tiny -- I will try again in a few splitting out HTTP::UserAgent to see if it handles things better. Attaching the build output here

[text.txt](https://github.com/jonathanstowe/JSON-Name/files/1117273/text.txt)

**Comment by adaptiveoptics** [comment]
Splitting it out with http::UserAgent first, then the build dies  on HTTP::Server::Tiny again, exactly the same as the previous text attached.

OK -- now today HTTP::Server::Tiny is just dying all over the place instead - not letting me get Crust installed even.

**Comment by jonathanstowe** [comment]
I'm going to close this as it was never to do with JSON::Name
