### ISSUE TITLE
JSON::Name fails tests on 2018.04

### ISSUE THREAD

**Issue by zostay** [jonathanstowe/JSON-Name#2]
Most of my Travis CI runs fail with this error for 2018.04. (I believe JSON::Name is in the dependency chain for Test::META, which I run on all my distros.)

```
===> Testing: JSON::Name:ver<0.0.3>:auth<github:jonathanstowe>:api<1.0>
# Failed test 'Can load "JSON::Name" ok'
# at t/010-use.t line 7
# ===SORRY!===
# Unexpected named argument 'api' passed
# 
# Looks like you failed 1 test of 1
===SORRY!===
Unexpected named argument 'api' passed
===> Testing [FAIL]: JSON::Name:ver<0.0.3>:auth<github:jonathanstowe>:api<1.0>
```

So far, the work around I'm using is either to drop testing on 2018.04 or add an allow_failures flag to the Travis config to make it so that 2018.04 still runs, but fails. The latter is not very useful as I can't proceed with any tests with 2018.04 because this failure happens while installing dependencies.

**Comment by jonathanstowe** [comment]
Okay that's a pain.  The ```:api``` adverb got added to the class definition at a later version than I thought.

This will effect *all* my modules including all but one of the dependencies of ```Test::META``` (and ```Test::META``` itself.)

It'll take me a couple of hours to re-up them without the ```:api```` so bear with me.

**Comment by jonathanstowe** [comment]
That should be all good now, I'd give it a while before re-testing as they're all on CPAN now.

**Comment by jonathanstowe** [comment]
I put back the testing on Travis testing with 2018.04 for ```Test::META``` and that is all good now https://travis-ci.org/jonathanstowe/Test-META/builds/501696562 - so you should be good to go.

As a matter of curiosity is there anything *special* about 2018.04 that means it should be tested for a long time or is it just an arbitrary, reasonably good, release?
